name: movie_tron
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  english_words: ^4.0.0
  provider: ^6.1.2
  flutter_svg: ^2.0.10+1
  http: ^1.2.1
  dio: ^5.5.0+1
  flutter_bloc: ^8.1.6

  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  bloc: ^8.1.4
  retrofit: ^4.1.0
  json_annotation: ^4.9.0
  pretty_dio_logger: ^1.3.1
  retrofit_generator: ^8.1.1
  shared_preferences: ^2.2.3
  carousel_slider: ^4.2.1
  flutter_rating_stars: ^1.1.0
  cached_network_image: ^3.4.0
  get_it: ^7.7.0
  injectable: ^2.4.4
  go_router: ^14.2.6
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  injectable_generator: ^2.4.4
  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.11

flutter:

  assets:
    - assets/image/
    - assets/image/bottom_navigation/
    - assets/image/detail_page/
    - assets/image/home_page/
    - assets/image/home_page/home_tiles/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700
  uses-material-design: true
  generate: true
flutter_intl:
  enabled: true
